<a href="https://colab.research.google.com/github/maniprasad84/2311cs020450/blob/main/classroom.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:
j=[9,4,5,6,3,2]
j

[9, 4, 5, 6, 3, 2]

In [ ]:
d=np.array(j)
d

array([9, 4, 5, 6, 3, 2])

In [ ]:
d.shape

(6,)

In [ ]:
d.size

6

In [ ]:
r=[3,5,4.4,5.5,6]
j

[9, 4, 5, 6, 3, 2]

In [ ]:
r=[3,5,4.4,5.5,6]
r

[3, 5, 4.4, 5.5, 6]

In [ ]:
y=[]
x=[]
for i in range (len(j)):
  if i%2==0:
    x.append(j[i])
  else:
    y.append(j[i])

In [ ]:
for i in j:
  print (i)

9
4
5
6
3
2


In [ ]:
range(len(j))


range(0, 6)

In [ ]:
for i in j:
  print (i)

9
4
5
6
3
2


In [ ]:
range(9)

range(0, 9)

In [ ]:
range(4)

range(0, 4)

In [ ]:
for i in range(len(j)):
  print(i)

0
1
2
3
4
5


In [ ]:
m=[20,30,80,64,57]
m

[20, 30, 80, 64, 57]

In [ ]:
np.quantile(m,0.25)

30.0

In [ ]:
np.quantile(m,0.5)

57.0

In [ ]:
np.quantile(m,0.75)

64.0

In [ ]:
np.random.rand()

0.9621229371411282

In [ ]:
np.random.rand(100)

array([0.6267113 , 0.51690249, 0.82982858, 0.85572274, 0.35168073,
       0.47380803, 0.88681544, 0.82938011, 0.17152841, 0.12119571,
       0.04937476, 0.10082517, 0.62038569, 0.2899846 , 0.64907873,
       0.71331583, 0.36905737, 0.69104265, 0.85342657, 0.07632408,
       0.88148182, 0.7858719 , 0.67538707, 0.38748048, 0.58298758,
       0.24425294, 0.38270356, 0.79885474, 0.74178311, 0.17416511,
       0.34463012, 0.31744426, 0.47208089, 0.25002225, 0.20693926,
       0.04834223, 0.70800644, 0.00101609, 0.56876011, 0.15294793,
       0.80276529, 0.58296597, 0.48292372, 0.11675535, 0.59621434,
       0.74301261, 0.64650456, 0.45131231, 0.3603744 , 0.37267195,
       0.43116862, 0.55852267, 0.04345709, 0.2109833 , 0.1567815 ,
       0.94603202, 0.13654417, 0.26024988, 0.23919498, 0.27239542,
       0.86765073, 0.97616425, 0.50450157, 0.84639602, 0.93868827,
       0.69330191, 0.21845537, 0.18640612, 0.60678403, 0.99981476,
       0.69909028, 0.13126802, 0.42725787, 0.18038557, 0.62138

In [ ]:
import numpy as np



In [ ]:
np.random.randn(10,4)

array([[-6.10558688e-01, -1.27768734e-01,  7.98943056e-01,
         1.79294235e+00],
       [-2.06970363e-01,  1.92499080e+00,  1.44662100e+00,
         2.13208237e-01],
       [-2.99012565e+00,  2.72664623e+00, -1.29744129e+00,
        -1.58943558e-01],
       [ 5.55353790e-01,  1.26203774e+00,  8.54175450e-01,
        -9.41948135e-03],
       [ 2.61392382e-01, -1.07370293e+00,  4.84470405e-01,
        -1.14388527e+00],
       [ 5.34197676e-01,  3.64783376e-01,  4.28971086e-01,
         3.29703404e-02],
       [ 1.67144390e+00,  8.64976466e-03, -4.04396951e-01,
         7.01049846e-01],
       [-9.10098223e-01, -1.66341889e+00, -2.02765536e-01,
        -1.79462511e+00],
       [-3.87166574e-04,  3.16656347e-01, -2.91543846e-01,
        -5.32740350e-01],
       [ 4.31618983e-02, -3.94390842e-01,  1.45249613e+00,
        -9.35472576e-01]])

In [ ]:
np.random.randint(5,66)

64

# New Section

In [ ]:
np.random.randint(35,86,(5,5))

array([[71, 54, 75, 69, 74],
       [55, 74, 40, 74, 80],
       [45, 59, 44, 45, 70],
       [55, 42, 68, 50, 40],
       [51, 80, 77, 54, 58]])